<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Badge;

class BadgeSeeder extends Seeder
{
    public function run()
    {
        $badges = [
            // 📊 CONSISTENCY BADGES
            [
                'name' => 'Early Bird',
                'description' => 'Selesaikan 10 habit sebelum jam 8 pagi',
                'icon' => '🌅',
                'category' => 'consistency',
                'requirement_type' => 'morning_completions',
                'requirement_target' => 10,
                'habit_type' => 'good',
                'reward_xp' => 150,
                'reward_coins' => 75,
            ],
            [
                'name' => 'Night Owl',
                'description' => 'Selesaikan 10 habit setelah jam 10 malam',
                'icon' => '🦉',
                'category' => 'consistency',
                'requirement_type' => 'night_completions',
                'requirement_target' => 10,
                'habit_type' => 'good',
                'reward_xp' => 150,
                'reward_coins' => 75,
            ],
            [
                'name' => 'Weekend Warrior',
                'description' => 'Sempurnakan semua habit di weekend 5 kali',
                'icon' => '💪',
                'category' => 'consistency',
                'requirement_type' => 'perfect_weekends',
                'requirement_target' => 5,
                'habit_type' => 'any',
                'reward_xp' => 200,
                'reward_coins' => 100,
            ],
            [
                'name' => 'Perfect Week',
                'description' => 'Selesaikan semua habit tanpa miss selama 1 minggu',
                'icon' => '⭐',
                'category' => 'consistency',
                'requirement_type' => 'perfect_week',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 250,
                'reward_coins' => 125,
            ],
            [
                'name' => 'Monthly Perfect',
                'description' => 'Bulan sempurna tanpa melewatkan habit apapun',
                'icon' => '🌟',
                'category' => 'consistency',
                'requirement_type' => 'perfect_month',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 800,
                'reward_coins' => 400,
            ],
            [
                'name' => '75% Success Rate',
                'description' => 'Pertahankan success rate 75% selama 30 hari',
                'icon' => '🎯',
                'category' => 'consistency',
                'requirement_type' => 'success_rate',
                'requirement_target' => 75,
                'habit_type' => 'any',
                'reward_xp' => 400,
                'reward_coins' => 200,
            ],

            // 🎓 MASTERY BADGES
            [
                'name' => 'Habit Builder',
                'description' => 'Selesaikan 50 good habits',
                'icon' => '🏗️',
                'category' => 'mastery',
                'requirement_type' => 'good_habit_completions',
                'requirement_target' => 50,
                'habit_type' => 'good',
                'reward_xp' => 200,
                'reward_coins' => 100,
            ],
            [
                'name' => 'Good Habit Master',
                'description' => 'Selesaikan 200 good habits',
                'icon' => '🎓',
                'category' => 'mastery',
                'requirement_type' => 'good_habit_completions',
                'requirement_target' => 200,
                'habit_type' => 'good',
                'reward_xp' => 600,
                'reward_coins' => 300,
            ],
            [
                'name' => 'Morning Routine Pro',
                'description' => 'Selesaikan morning routine 25 kali',
                'icon' => '☀️',
                'category' => 'mastery',
                'requirement_type' => 'morning_routine_completions',
                'requirement_target' => 25,
                'habit_type' => 'good',
                'reward_xp' => 300,
                'reward_coins' => 150,
            ],
            [
                'name' => 'Temptation Resister',
                'description' => 'Hindari 25 bad habits',
                'icon' => '🛡️',
                'category' => 'mastery',
                'requirement_type' => 'bad_habit_avoided',
                'requirement_target' => 25,
                'habit_type' => 'bad',
                'reward_xp' => 250,
                'reward_coins' => 125,
            ],
            [
                'name' => 'Self Control Master',
                'description' => 'Hindari 100 bad habits',
                'icon' => '🧠',
                'category' => 'mastery',
                'requirement_type' => 'bad_habit_avoided',
                'requirement_target' => 100,
                'habit_type' => 'bad',
                'reward_xp' => 700,
                'reward_coins' => 350,
            ],
            [
                'name' => 'Clean Slate',
                'description' => 'Hindari semua bad habits selama 7 hari berturut-turut',
                'icon' => '✨',
                'category' => 'mastery',
                'requirement_type' => 'bad_habit_streak',
                'requirement_target' => 7,
                'habit_type' => 'bad',
                'reward_xp' => 400,
                'reward_coins' => 200,
            ],
            [
                'name' => 'Level 10 Achiever',
                'description' => 'Capai level 10',
                'icon' => '🔟',
                'category' => 'mastery',
                'requirement_type' => 'level',
                'requirement_target' => 10,
                'habit_type' => 'any',
                'reward_xp' => 500,
                'reward_coins' => 250,
            ],
            [
                'name' => 'Halfway There',
                'description' => 'Capai level 25',
                'icon' => '🎯',
                'category' => 'mastery',
                'requirement_type' => 'level',
                'requirement_target' => 25,
                'habit_type' => 'any',
                'reward_xp' => 1200,
                'reward_coins' => 600,
            ],
            [
                'name' => 'Habit Master',
                'description' => 'Capai level 50',
                'icon' => '👑',
                'category' => 'mastery',
                'requirement_type' => 'level',
                'requirement_target' => 50,
                'habit_type' => 'any',
                'reward_xp' => 3000,
                'reward_coins' => 1500,
            ],

            // 🌈 VARIETY BADGES
            [
                'name' => 'Jack of All Trades',
                'description' => 'Buat 10 habit berbeda',
                'icon' => '🎭',
                'category' => 'variety',
                'requirement_type' => 'unique_habits',
                'requirement_target' => 10,
                'habit_type' => 'any',
                'reward_xp' => 300,
                'reward_coins' => 150,
            ],
            [
                'name' => 'Balanced Life',
                'description' => 'Miliki 5 good habits dan 3 bad habits yang di-track',
                'icon' => '⚖️',
                'category' => 'variety',
                'requirement_type' => 'balanced_habits',
                'requirement_target' => 8, // total habits
                'habit_type' => 'any',
                'reward_xp' => 400,
                'reward_coins' => 200,
            ],

            // 🎉 SPECIAL BADGES
            [
                'name' => 'Comeback Kid',
                'description' => 'Kembali tracking setelah break 3 hari',
                'icon' => '🔄',
                'category' => 'special',
                'requirement_type' => 'comeback',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 100,
                'reward_coins' => 50,
            ],
            [
                'name' => 'Resilient Soul',
                'description' => 'Kembali setelah break 1 minggu dan pertahankan streak 7 hari',
                'icon' => '💫',
                'category' => 'special',
                'requirement_type' => 'resilient_comeback',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 500,
                'reward_coins' => 250,
            ],
            [
                'name' => 'First Blood',
                'description' => 'Selesaikan habit pertama kamu!',
                'icon' => '🎊',
                'category' => 'special',
                'requirement_type' => 'first_completion',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 50,
                'reward_coins' => 25,
            ],
            [
                'name' => 'Week 1 Survivor',
                'description' => 'Selesaikan minggu pertama tracking habits',
                'icon' => '🎖️',
                'category' => 'special',
                'requirement_type' => 'first_week',
                'requirement_target' => 1,
                'habit_type' => 'any',
                'reward_xp' => 150,
                'reward_coins' => 75,
            ],
            [
                'name' => 'Habit Explorer',
                'description' => 'Gunakan app selama 30 hari berturut-turut',
                'icon' => '🧭',
                'category' => 'special',
                'requirement_type' => 'app_usage_days',
                'requirement_target' => 30,
                'habit_type' => 'any',
                'reward_xp' => 600,
                'reward_coins' => 300,
            ],
        ];

        foreach ($badges as $badge) {
            Badge::create($badge);
        }

        $this->command->info('🎉 ' . count($badges) . ' badges berhasil ditambahkan!');
    }
}